# audios de fondo
define audio.Alone = './audio/Alone.mp3'
define audio.Autonomy = './audio/Autonomy.mp3'
define audio.ColorYourNight = './audio/Color Your Night.mp3'
define audio.IReallyWantYou = './audio/I Really Want to Stay at Your House.mp3'
define audio.LastGoodbye = './audio/Last Goodbye.mp3'
define audio.nothingCanBeExplained = './audio/nothing can be explained.mp3'
define audio.OceanOfMemories = './audio/Ocean of Memories.mp3'
define audio.OnceUponAtime = './audio/Once Upon a Time.mp3'
define audio.RightBehindYou = './audio/Right Behind You.mp3'
define audio.SunsetBridge = './audio/Sunset Bridge.mp3'
define audio.WithASmile = './audio/With a Smile.mp3'
define audio.StillLoveYou = './audio/Still I Love You.mp3'
define audio.FruitBasket = './audio/Fruits Basket soundtrack 2.mp3'
define audio.NextToYou = './audio/NEXT TO YOU.mp3'
define audio.StayWithMe = './audio/Stay With Me.mp3'
# efectos de sonido
define audio.TitleEffect = './audio/Undertale Sound Effect Intro.mp3'
define audio.Salvation = './audio/FNAF - 6 AM sound.mp3'
define audio.RoadNoise = './audio/road-noise-1.mp3'
define audio.FairNoise = './audio/street-fair-background-noise-149086.mp3'